service: try-golang-on-lambda

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: my

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    memorySize: 128
    events:
      - http:
          path: '/'
          method: get
  # world:
  #   handler: bin/world
  #   memorySize: 128
  #   events:
  #     - http:
  #         path: '/world'
  #         method: get
